[package]
name = "rust-axum-app"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rust-axum-app"
path = "src/main.rs"

[dependencies]
axum = "0.8.3"
tokio = { version = "1.44.1", features = ["full"] }